spring.application.name=Library-Management-System

# Database connection (change the password to yours)
spring.datasource.url=jdbc:mysql://localhost:3306/library_db
spring.datasource.username=root
spring.datasource.password=********

# Let Hibernate create the tables from our Java classes
spring.jpa.hibernate.ddl-auto=update

# Print the SQL in the console so we can learn from it
spring.jpa.show-sql=true

# Good practice: keep database work inside services
spring.jpa.properties.hibernate.format_sql=true

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50
